version: "3.8"

networks:
  selenoid:
    name: selenoid

services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - $PWD:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "-conf", "/etc/selenoid/browsers.json",
        "-service-startup-timeout", "5m0s",
        "-session-attempt-timeout", "5m0s",
        "-session-delete-timeout", "5m0s",
        "-timeout", "5m0s",
        "-container-network", "selenoid"
      ]
    ports:
      - 4444:4444
    networks:
      - selenoid

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:latest-release
    depends_on:
      - selenoid
    links:
      - selenoid
    command:
      [
        "--selenoid-uri", "http://selenoid:4444"
      ]
    ports:
      - 8081:8080
    networks:
      - selenoid
