name: Run UI-Automation Tests

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 6 * * 0-6'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SELENOID: '127.0.0.1'
      BROWSER_VERSION: '88.0'

    steps:
      - uses: actions/checkout@v1

      - name: Configure browsers.json
        run: npm run configure:browsers

      - name: Set up Selenoid
        run: npm run selenoid:start

      - name: Run UI Tests
        run: npm cit

      - name: Shutdown Selenoid
        run: npm run selenoid:stop

      - name: Generate Allure Report
        if: always()
        run: npm run report-ci

      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure report
          path: ./allure-report
