name: Running UI-Automation Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set workdir to browsers.json as mount
        run: make workdir

      - name: Set up Selenoid Infrastructure
        run: make setup

      - name: Install npm dependencies
        run: npm install

      - name: Run UI-Automation tests with Chrome browser
        env:
          SELENOID: '127.0.0.1'
        run: npm cit

      - name: Shutdown Selenoid Infrastructure
        run: make stop
